name: CI

on:
  pull_request:
    branches:
    - 'feat/*'
    - 'develop'
    
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: JDK11 설치
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: 빌드
      run: ./gradlew build -x test
      
    - name: 테스트
      run: ./gradlew test

    - name: 단위테스트 결과 
      if: always()
      uses: EnricoMi/publish-unit-test-result-action@v1
      with:
        junit: '**/build/test-results/test/*.xml'
        github_token: ${{ secrets.TOKEN }}
  
